# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: your-email@domain.com
brand: Yashpal
headline: Learner, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "jekyll-instagram-portfolio-theme" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: ahlawatyashpal8@gmail.com
phone: 9466428221

# Tracking
googleAnalitycsID: UA-83933844-1

